### ISSUE TITLE
package.txt

### ISSUE THREAD

**Issue by ghost** [dokku-alt/progrium-buildstep-dockerfiles#9]
Hi
I only use https://github.com/heroku/heroku-buildpack-php.git and deleted other from buildpacks.txt file.
i want to delete unnecessery package.txt and i dont know how packages are necessary for php.

My goal is to decrease size of buildstep image.

please help me

Thanks

**Comment by ayufan** [comment]
Currently is cedar-14 used as default. Please change Github's branch.

On Thursday, January 8, 2015, amirarabi notifications@github.com wrote:

> Hi
> I only use https://github.com/heroku/heroku-buildpack-php.git and deleted
> other from buildpacks.txt file.
> i want to delete unnecessery package.txt and i dont know how packages are
> necessary for php.
> 
> My goal is to decrease size of buildstep image.
> 
> please help me
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dokku-alt/progrium-buildstep-dockerfiles/issues/9.

## 

Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by ghost** [comment]
Ok
because i use only php buildpack for my project, How can reduce ayufan/dokku-alt-buildstep:cedar-14 image size (1.02 GB)?

Thanks
